{% set name = "pgcolorbar" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pgcolorbar-{{ version }}.zip
  sha256: 4cfc9e389362564425935d98d14833a4c3f3f32fc60ce6398a37166b0e6d203d

build:
  number: 0
  noarch: python
  entry_points:
    - pgcolorbar_demo = pgcolorbar.demo:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - pyqtgraph >=0.10.0
    - python >=3.5

test:
  imports:
    - pgcolorbar
  commands:
    - pip check
  requires:
    - pip
    - pyqt >=5.12

about:
  home: https://github.com/titusjan/pgcolorbar
  summary: PgColorbar is a color bar for PyQtGraph image plots.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - titusjan
